services:
  - type: web
    name: your-service-name
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python your_start_script.py
    pythonVersion: "3.12.13"
